#ddev-generated
services:
  phpmyadmin:
    container_name: ddev-${DDEV_SITENAME}-phpmyadmin
    image: ${PHPMYADMIN_DOCKER_IMAGE:-phpmyadmin/phpmyadmin:latest}
    hostname: ${PHPMYADMIN_HOSTNAME:-phpmyadmin}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    restart: "no"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=db
      - PMA_PASSWORD=db
      - UPLOAD_LIMIT=300M
      - MEMORY_LIMIT=256M
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8036:80
      - HTTPS_EXPOSE=8037:80
    expose:
      - 80
    links:
      - db:db
    depends_on:
      - db
    x-ddev:
      describe-url-port: |
        phpMyAdmin: https://${DDEV_HOSTNAME}:8037
      describe-info: |
        Username: db
        Password: db
